from __future__ import annotations

"""Qwen platform constants.

This module intentionally carries the broad platform-level constant surface
expected by the adapter itself and by legacy compatibility imports.
"""

from typing import Dict, Final, List

from .endpoints import (
    BAXIA_SDK_VERSION,
    BASE_URL,
    BXUA_VERSION,
    COOKIE_REFRESH_INTERVAL,
    CUSTOM_BASE64_CHARS,
    FRONTEND_VERSION,
    GENERATED_IMAGE_DIR,
    GENERATED_VIDEO_DIR,
    INITIAL_LOGIN_MAX,
    LOGIN_BATCH,
    LOGIN_BATCH_SIZE,
    LOGIN_CONCURRENCY,
    LOGIN_POLL_INTERVAL,
    LOGIN_POOL_SIZE,
    LOGIN_SELECT_MAX,
    LOGIN_SELECT_MIN,
    MODELS_PERSIST_PATH,
    PERSIST_INTERVAL,
    PERSIST_PATH,
    PROXY_SELECTOR_PERSIST_PATH,
    SEC_CH_UA,
    SSE_TIMEOUT,
    TASK_TIMERS_PATH,
    TOKEN_EXPIRY_MARGIN,
    TOKEN_REFRESH_INTERVAL,
    TTS_DIR,
    TTS_TIMEOUT,
    UPLOAD_TEMP_DIR,
    USER_AGENT,
    USER_AGENT_MOBILE,
    VIDEO_CDN_BASE,
    VIDEO_TASK_MAX_POLL_TIME,
    VIDEO_TASK_POLL_INTERVAL,
)

MODELS: Final[List[str]] = [
    "qwen3.6-plus",
    "qwen3.5-plus",
    "qwen3.5-397b-a17b",
    "qwen3-max",
    "qwen3-max-2026-01-23",
    "qwen3-235b-a22b",
    "qwen3-30b-a3b",
    "qwen3-vl-30b-a3b",
    "qwen3-vl-32b",
    "qwen3-vl-plus",
    "qwen3-coder-plus",
    "qwen3-coder-30b-a3b-instruct",
    "qwen3-omni-flash",
    "qwen3-omni-flash-2025-12-01",
    "qwen2.5-72b-instruct",
    "qwen2.5-vl-32b-instruct",
    "qwen2.5-omni-7b",
    "qwen2.5-coder-32b-instruct",
    "qwen-max-latest",
    "qwen-plus-2025-07-28",
    "qwen-plus-2025-09-11",
    "qwen-plus-2025-01-25",
    "qwen-turbo-2025-02-11",
]

CAPS: Final[Dict[str, bool]] = {
    "chat": True,
    "vision": True,
    "thinking": True,
    "search": True,
    "image_gen": True,
    "image_edit": True,
    "audio_gen": True,
    "video_gen": True,
    "continuation": True,
    "artifacts": True,
}

SMART_PROXY_ENABLED: Final[bool] = True

__all__ = [
    "BASE_URL",
    "USER_AGENT",
    "USER_AGENT_MOBILE",
    "SEC_CH_UA",
    "FRONTEND_VERSION",
    "BAXIA_SDK_VERSION",
    "BXUA_VERSION",
    "CUSTOM_BASE64_CHARS",
    "MODELS",
    "CAPS",
    "MODELS_PERSIST_PATH",
    "PERSIST_PATH",
    "TASK_TIMERS_PATH",
    "PROXY_SELECTOR_PERSIST_PATH",
    "GENERATED_IMAGE_DIR",
    "GENERATED_VIDEO_DIR",
    "TTS_DIR",
    "UPLOAD_TEMP_DIR",
    "SMART_PROXY_ENABLED",
    "LOGIN_BATCH",
    "LOGIN_BATCH_SIZE",
    "LOGIN_CONCURRENCY",
    "LOGIN_POOL_SIZE",
    "LOGIN_SELECT_MIN",
    "LOGIN_SELECT_MAX",
    "INITIAL_LOGIN_MAX",
    "LOGIN_POLL_INTERVAL",
    "TOKEN_EXPIRY_MARGIN",
    "TOKEN_REFRESH_INTERVAL",
    "COOKIE_REFRESH_INTERVAL",
    "PERSIST_INTERVAL",
    "SSE_TIMEOUT",
    "TTS_TIMEOUT",
    "VIDEO_CDN_BASE",
    "VIDEO_TASK_MAX_POLL_TIME",
    "VIDEO_TASK_POLL_INTERVAL",
]
