/**
 * Per-tab lazy-load resource manifest, consumed by lazy.js (LazyLoader).
 * Split out of lazy.js as a data-only sibling file.
 */
var LAZY_TAB_RESOURCES = {
  dashboard: [
    { type: 'js', url: '/static/features/stats/stats_cardshelpers.js?v=20260717-1' },
    { type: 'js', url: '/static/features/stats/stats_cards.js?v=20260716-1' },
    { type: 'js', url: '/static/features/stats/stats_helpers.js?v=20260717-1' },
    { type: 'js', url: '/static/features/stats/stats.js?v=20260717-1' },
    { type: 'js', url: '/static/features/dash.js?v=20260709-1' },
  ],
  routing: [
    { type: 'js', url: '/static/features/routing.js?v=20260709-1' },
  ],
  keys: [
    { type: 'js', url: '/static/features/keys_helpers.js?v=20260717-1' },
    { type: 'js', url: '/static/features/keys.js?v=20260717-1' },
  ],
  requests: [
    { type: 'js', url: '/static/features/stats/inspector/insp_list.js?v=20260716-1' },
    { type: 'js', url: '/static/features/stats/inspector/insp_detail.js?v=20260716-1' },
    { type: 'js', url: '/static/features/stats/inspector/insp_core.js?v=20260716-1' },
  ],
  settings: [
    { type: 'css', url: '/static/ui/sortable-list/sort.css' },
    { type: 'js',  url: '/static/ui/sortable-list/sort_helpers.js' },
    { type: 'js',  url: '/static/ui/sortable-list/sort.js' },
  ],
  terminal: [
    { type: 'css', url: '/static/vendor/xterm/xterm.css' },
    { type: 'css', url: '/static/base/core/tabbar/tabbar.css' },
    { type: 'css', url: '/static/ui/terminal/term.css' },
    { type: 'js',  url: '/static/vendor/xterm/xterm.js' },
    { type: 'js',  url: '/static/vendor/xterm/addon-fit.js' },
    { type: 'js',  url: '/static/vendor/xterm/addon-canvas.js' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_core.js?v=20260716-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_status.js?v=20260716-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_preview.js?v=20260716-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_render.js?v=20260716-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_crud.js?v=20260716-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_color.js?v=20260718-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_layout.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/core/term_links.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/core/term_pane.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/core/term_resize.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/core/term_splitpersist.js?v=20260722-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/core/term_init.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/interact/term_search.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/appearance/term_thumb.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/appearance/term_theme.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/appearance/term_color.js?v=20260718-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/interact/term_ctxitems.js?v=20260720-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/interact/term_ctxmenu.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/session/term_split.js?v=20260722-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/session/term_chooser.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/session/term_ssh.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/session/term_lfcycle.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/session/wshndl.js?v=20260722-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/session/term_wsock.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/session/term_recon.js?v=20260722-1' },
    { type: 'js',  url: '/static/ui/terminal/terminal/core/term_tabops.js?v=20260722-1' },
    { type: 'js',  url: '/static/ui/terminal/term.js?v=20260717-1' },
    { type: 'js',  url: '/static/ui/terminal/sidebar/servers.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/sidebar/audit.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/sidebar/cmds.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/sidebar/dialogs.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/sidebar/core.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/terminal/sidebar.js?v=20260716-1' },
  ],
  files: [
    { type: 'css', url: '/static/vendor/highlightjs/github-dark.min.css' },
    { type: 'js',  url: '/static/vendor/highlightjs/highlight.min.js' },
    { type: 'css', url: '/static/base/core/tabbar/tabbar.css' },
    { type: 'css', url: '/static/features/files/files.css?v=20260718-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_core.js?v=20260716-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_status.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/state.js?v=20260718-1' },
    { type: 'js',  url: '/static/features/files/modules/m5/ops.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/m6/search.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/m1/dirlist.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/m3/table.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/m3/render.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/m4/toolbar.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/m3/menu.js?v=20260718-1' },
    { type: 'js',  url: '/static/features/files/modules/m3/color.js?v=20260718-1' },
    { type: 'js',  url: '/static/features/files/modules/m6/preview_host.js?v=20260720-1' },
    { type: 'js',  url: '/static/features/files/modules/m6/preview.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/m4/upload.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/m2/editor_tmpl.js?v=20260716-2' },
    { type: 'js',  url: '/static/features/files/modules/m2/editor_window.js?v=20260716-2' },
    { type: 'js',  url: '/static/features/files/modules/m1/editor.js?v=20260716-2' },
    { type: 'js',  url: '/static/features/files/modules/m2/editor_body.js?v=20260716-2' },
    { type: 'js',  url: '/static/features/files/modules/m1/edtree.js?v=20260716-2' },
    { type: 'js',  url: '/static/features/files/modules/m5/kbd_nav.js?v=20260720-1' },
    { type: 'js',  url: '/static/features/files/modules/m5/kbd.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/modules/m4/tabs.js?v=20260718-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_preview.js?v=20260716-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_render.js?v=20260716-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_crud.js?v=20260716-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_color.js?v=20260718-1' },
    { type: 'js',  url: '/static/base/core/tabbar/tabbar_all/tabbar_layout.js?v=20260716-1' },
    { type: 'js',  url: '/static/features/files/files.js?v=20260716-1' },
  ],
  chat: [
    { type: 'css', url: '/static/vendor/highlightjs/github-dark.min.css' },
    { type: 'css', url: '/static/features/files/files.css?v=20260709-6' },
    { type: 'css', url: '/static/ui/widgets/inputbox/inbox.css' },
    { type: 'js',  url: '/static/vendor/highlightjs/highlight.min.js' },
    { type: 'js',  url: '/static/ui/widgets/inputbox/inbox_core.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/widgets/inputbox/inbox_events.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/widgets/inputbox/inbox_send.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/widgets/inputbox/inbox_voice.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/widgets/inputbox/inbox_api.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/chat/attachments/viewer/attach_vwshare.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/viewer/attach_vwimg.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/viewer/attach_vwvid.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/viewer/attach_viewer.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/preview/attach_pvmkup.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/preview/attach_pvbody.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/preview/attach_pvdtl.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/preview/attach_preview.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/collect/collect_parts.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/collect/collect_tiles.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/collect/collect_root.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/attach_collect.js?v=20260716-5' },
    { type: 'js',  url: '/static/ui/chat/attachments/attach_events.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/chat/attachments/attach_helpers.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/chat/attach.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/chat/medips/medips_util.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/chat/medips/medips_exporthelpers.js?v=20260717-1' },
    { type: 'js',  url: '/static/ui/chat/medips/medips_export.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/chat/medips/medips_hydrate.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/chat/medips/medips.js?v=20260716-1' },
    { type: 'js',  url: '/static/ui/chat/chat_all/chat_render.js?v=20260717-3' },
    { type: 'js',  url: '/static/ui/chat/chat_all/chat_tools.js?v=20260717-3' },
    { type: 'js',  url: '/static/ui/chat/chat_all/chat_persist.js?v=20260717-3' },
    { type: 'js',  url: '/static/ui/chat/chat_all/chat.js?v=20260717-3' },
    { type: 'js',  url: '/static/ui/chat/chat_all/chat_actions.js?v=20260717-3' },
    { type: 'js',  url: '/static/ui/chat/chat_all/chat_send.js?v=20260717-3' },
    { type: 'js',  url: '/static/ui/chat/chat_all/chat_batch.js?v=20260717-3' },
  ],
  stats: [
    { type: 'js', url: '/static/features/stats/stats_cardshelpers.js?v=20260717-1' },
    { type: 'js', url: '/static/features/stats/stats_cards.js?v=20260716-1' },
    { type: 'js', url: '/static/features/stats/stats_helpers.js?v=20260717-1' },
    { type: 'js', url: '/static/features/stats/stats.js?v=20260717-1' },
    { type: 'js', url: '/static/features/stats/inspector/insp_list.js?v=20260716-1' },
    { type: 'js', url: '/static/features/stats/inspector/insp_detail.js?v=20260716-1' },
    { type: 'js', url: '/static/features/stats/inspector/insp_core.js?v=20260716-1' },
  ],
  config: [],
  autoupdate: [
    { type: 'css', url: '/static/ui/sortable-list/sort.css' },
    { type: 'js',  url: '/static/ui/sortable-list/sort_helpers.js' },
    { type: 'js',  url: '/static/ui/sortable-list/sort.js' },
  ],
  plugins: [
    { type: 'css', url: '/static/features/plugins/plugins.css?v=20260710-1' },
    { type: 'js', url: '/static/features/plugins/logic/plugins_helpers.js?v=20260717-1' },
    { type: 'js', url: '/static/features/plugins/logic/plugins_rlist.js?v=20260717-1' },
    { type: 'js', url: '/static/features/plugins/logic/plugins_rmkt.js?v=20260717-1' },
    { type: 'js', url: '/static/features/plugins/logic/plugins_redit.js?v=20260717-1' },
    { type: 'js', url: '/static/features/plugins/logic/plugins_actions.js?v=20260717-1' },
    { type: 'js', url: '/static/features/plugins/logic/plugins_events.js?v=20260717-1' },
    { type: 'js', url: '/static/features/plugins/plugins.js?v=20260717-1' },
  ],
};
